### ISSUE TITLE
increase <number> does not increase beyond 100

### ISSUE THREAD

**Issue by rohshall** [falconindy/ponymix#45] opened 2017-02-10 03:11 UTC
pulse does not have 100 as the limit. I can do "set-volume 120", and it works. So, increase should check the max volume level, and allow the increase, instead of maxing it out at 100.

**Comment by falconindy** [comment] 2017-02-10 18:30
This is working as designed -- the limit of 100 via "increase" is meant as a safety measure. If you know that you want to increase the volume above 100, then you can override by using set-volume.

**Comment by falconindy** [comment] 2017-02-10 18:30
Perhaps a --max-volume flag could be added to change this behavior.

**Comment by rohshall** [comment] 2017-02-10 18:38
My understanding, from using GUI like pavucontrol, is that these devices have max limit anyway - like 150. So, it anyway gets clamped at say, 150. 
The problem I am facing is I have mapped my i3 keybindings to increase and decrese by 10%. And then it gets clamped at 100. So, I have to manually type the command "set-volume" to increase the volume.

**Comment by vodik** [comment] 2017-02-10 19:50
There has long been a max-volume flag:

```
$ ponymix increase 150
100
$ ponymix increase 150 --max-volume 150
150
```

But warning, likely will clip your speakers like crazy. If pulseaudio isn't getting loud enough at 100, something else is wrong - this is just a workaround.

**Comment by falconindy** [comment] 2017-02-10 20:03
Ah good job me, I already added this 4 years ago. So then this is just a dupe of https://github.com/falconindy/ponymix/issues/19.

**Closed by falconindy** 2017-02-10 20:03 UTC
